Squashed commit of the following:
commit 1f3b554aceb0dbcec04305771694c4b78e757719
Author: おるとろ <kazmax7@gmail.com>
Date:   Mon Mar 10 13:47:50 2025 +0900

    Fix/chore (#3)

    * fix: build fails

    * Enable lfs for font

    * remove track fonts

    * track fonts with lfs

    * Add: Ci

commit 8a026f000f65b2ba590159ec77fab2c20d9ff107
Author: おるとろ <kazmax7@gmail.com>
Date:   Mon Mar 10 10:57:31 2025 +0900

    Feat/cycle (#1)

    * Enable: Change Work or Break

    * Enable: update cycles by date

    * refactor

    * Add complete button

    * Add: pre-push

    * i18n

commit 85410633492e7f910be0f490b414c08b30247d6e
Author: kawadumax <kazmax7@gmail.com>
Date:   Fri Mar 7 13:53:31 2025 +0900

    Update: deploy with pnpm

commit 8ee3956fcee7952c749d1fb69b46079f0d086a4c
Author: kawadumax <kazmax7@gmail.com>
Date:   Fri Mar 7 12:12:06 2025 +0900

    Change: Using pnpm

commit 721f5181298bf0d620ee8e25d48c7b2ba64aa605
Author: kawadumax <kazmax7@gmail.com>
Date:   Fri Mar 7 11:48:14 2025 +0900

    Refactor: set with simple arrow function

commit 37e86361d647946e85d5f2f216a231c6b9fbef11
Merge: c54a46c 511e169
Author: kawadumax <kazmax7@gmail.com>
Date:   Fri Mar 7 11:25:43 2025 +0900

    Merge branch 'fix' into dev

commit 511e169030443cf1f21963b640fb674e3ce46869
Author: kawadumax <kazmax7@gmail.com>
Date:   Fri Mar 7 11:24:37 2025 +0900

    Fix: disappear tag when title is updated

diff --git a/.githooks/pre-push b/.githooks/pre-push
--- a/.githooks/pre-push
+++ b/.githooks/pre-push
@@ -1,38 +1,3 @@
-#!/bin/bash
-
-# 変更されたファイルを取得
-CHANGED_FILES=$(git diff --name-only HEAD @{push})
-
-# en.jsonとja.jsonが変更されているか確認
-EN_CHANGED=false
-JA_CHANGED=false
-
-for FILE in $CHANGED_FILES; do
-    if [[ "$FILE" == "en.json" ]]; then
-        EN_CHANGED=true
-    elif [[ "$FILE" == "ja.json" ]]; then
-        JA_CHANGED=true
-    fi
-done
-
-# どちらか一方が変更されていた場合は、キーの整合性をチェック
-if [[ "$EN_CHANGED" == "true" || "$JA_CHANGED" == "true" ]]; then
-    echo "Checking JSON key consistency..."
-
-    # JSONのキーを取得
-    EN_KEYS=$(jq -r 'keys_unsorted | .[]' en.json | sort)
-    JA_KEYS=$(jq -r 'keys_unsorted | .[]' ja.json | sort)
-
-    # 比較
-    DIFF=$(diff <(echo "$EN_KEYS") <(echo "$JA_KEYS"))
-
-    if [[ -n "$DIFF" ]]; then
-        echo "Error: JSON keys in en.json and ja.json do not match!"
-        echo "$DIFF"
-        echo "Please update ja.json to match en.json (or vice versa) before pushing."
-        exit 1
-    fi
-fi
-
-# プッシュを許可
-exit 0
+#!/bin/sh
+command -v git-lfs >/dev/null 2>&1 || { echo >&2 "\nThis repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting .git/hooks/pre-push.\n"; exit 2; }
+git lfs pre-push "$@"
